import { Listing, User, AdminAction, MetalMarketSpot } from "./types";

export const SEED_USERS: User[] = [
  {
    id: "usr_buyer_ravi",
    name: "Ravi Kumar",
    email: "ravi.k@example.com",
    role: "user",
    status: "active",
    trustScore: 4.9,
    city: "Bengaluru, KA",
  },
  {
    id: "usr_seller_priya",
    name: "Priya Sharma",
    email: "priya.tech@example.com",
    role: "user",
    status: "active",
    trustScore: 4.8,
    city: "Bengaluru, KA",
  },
  {
    id: "usr_admin_mehra",
    name: "Officer Vikram Mehra",
    email: "admin@recircuit.in",
    role: "admin",
    status: "active",
    trustScore: 5.0,
    city: "New Delhi, DL",
    twoFactorEnabled: true,
  },
];

export const METAL_MARKET_SPOTS: MetalMarketSpot[] = [
  { metal: "Clean Copper Wire", code: "Cu-No1", unit: "kg", rateINR: 645, trend: "up", changePct: 2.4 },
  { metal: "Extruded Aluminum", code: "Al-6063", unit: "kg", rateINR: 195, trend: "stable", changePct: 0.2 },
  { metal: "Gold-Finger PCB Boards", code: "PCB-Au", unit: "kg", rateINR: 1480, trend: "up", changePct: 4.1 },
  { metal: "High-Grade Tin/Solder", code: "Sn-63", unit: "kg", rateINR: 1820, trend: "down", changePct: -1.1 },
  { metal: "Mixed Shredded E-Scrap", code: "ESC-Gen", unit: "kg", rateINR: 320, trend: "up", changePct: 1.5 },
];

export const SEED_LISTINGS: Listing[] = [
  {
    id: "lst_hp_charger_01",
    sellerId: "usr_seller_priya",
    sellerName: "Priya Sharma",
    sellerTrust: 4.8,
    categoryId: "cat_cables_chargers",
    categoryName: "Cables & Chargers",
    title: "HP 65W Smart AC Adapter (Frayed Cable / Tip Functional)",
    description: "Original OEM HP Blue Pin 65W laptop charger. Outer rubber sheath is cracked near the DC barrel plug from bending, but inner copper conductors and barrel connector still deliver solid 19.5V. Great for repair, splicing, or copper wire recovery.",
    condition: "partial",
    suggestedPrice: 220,
    suggestedPriceMin: 180,
    suggestedPriceMax: 260,
    askingPrice: 220,
    scrapWeightKg: 0.28,
    scrapValueEst: 92,
    status: "active",
    city: "Indiranagar, Bengaluru",
    isHazardous: false,
    hazardDisclosed: false,
    images: [
      "https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80",
    ],
    scanResult: {
      id: "scn_hp_01",
      listingId: "lst_hp_charger_01",
      detectedBrand: "HP (Hewlett-Packard)",
      detectedModel: "PPP009L-E / 65W Smart Blue Tip",
      detectedCondition: "partial",
      confidenceScore: 0.94,
      suggestedPriceMin: 180,
      suggestedPriceMax: 260,
      scrapValueEst: 92,
      materialsBreakdown: [
        { name: "Copper core conductor", weightKg: 0.12, ratePerKg: 645, estimatedValue: 77.4 },
        { name: "High-impact ABS housing", weightKg: 0.16, ratePerKg: 90, estimatedValue: 14.4 },
      ],
      detectedFlaws: [
        "Frayed strain relief collar on DC lead",
        "Scuff marks on primary transformer chassis",
        "Barrel connector center pin intact",
      ],
      isHazardous: false,
      modelVersion: "vision-e-waste-v1.4",
      createdAt: new Date().toISOString(),
    },
    viewsCount: 148,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: "lst_dell_laptop_02",
    sellerId: "usr_seller_priya",
    sellerName: "Priya Sharma",
    sellerTrust: 4.8,
    categoryId: "cat_laptops_desktops",
    categoryName: "Laptops & Desktops",
    title: "Dell Latitude E7470 (Broken Screen, Working Motherboard & i5 CPU)",
    description: "Display glass and LCD matrix cracked during transit. Motherboard boots cleanly to external HDMI, i5-6300U processor, cooling fan, battery, and 8GB DDR4 RAM stick are 100% verified working. Selling for parts harvest or headless home server project.",
    condition: "for_parts",
    suggestedPrice: 2600,
    suggestedPriceMin: 2200,
    suggestedPriceMax: 3100,
    askingPrice: 2500,
    scrapWeightKg: 1.55,
    scrapValueEst: 640,
    status: "active",
    city: "Koramangala, Bengaluru",
    isHazardous: false,
    hazardDisclosed: true,
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=900&q=80",
    ],
    scanResult: {
      id: "scn_dell_02",
      listingId: "lst_dell_laptop_02",
      detectedBrand: "Dell",
      detectedModel: "Latitude E7470 14-inch Ultrabook",
      detectedCondition: "for_parts",
      confidenceScore: 0.92,
      suggestedPriceMin: 2200,
      suggestedPriceMax: 3100,
      scrapValueEst: 640,
      materialsBreakdown: [
        { name: "Magnesium-alloy chassis", weightKg: 0.65, ratePerKg: 280, estimatedValue: 182 },
        { name: "Multi-layer FR4 Motherboard + CPU", weightKg: 0.35, ratePerKg: 1100, estimatedValue: 385 },
        { name: "Copper heatsink & heatpipe", weightKg: 0.11, ratePerKg: 645, estimatedValue: 71 },
      ],
      detectedFlaws: [
        "Major spiderweb display fracture",
        "Display backlight inverter offline",
        "Motherboard POST lights green",
      ],
      isHazardous: false,
      modelVersion: "vision-e-waste-v1.4",
      createdAt: new Date().toISOString(),
    },
    viewsCount: 312,
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: "lst_crt_sony_03",
    sellerId: "usr_buyer_ravi",
    sellerName: "Ravi Kumar",
    sellerTrust: 4.9,
    categoryId: "cat_crt_heavy",
    categoryName: "CRT & Heavy Tech (Regulated)",
    title: "Sony Trinitron 17-Inch CRT Display (Deflection Yoke Salvage)",
    description: "Classic Sony Trinitron monitor. Power supply does not strike tube, heavy phosphor screen intact. Contains heavy copper deflection yoke (~1.2 kg pure copper windings) plus analog PCB circuitry. Regulated e-waste due to lead glass envelope.",
    condition: "for_parts",
    suggestedPrice: 580,
    suggestedPriceMin: 450,
    suggestedPriceMax: 750,
    askingPrice: 600,
    scrapWeightKg: 16.4,
    scrapValueEst: 920,
    status: "pending_review", // Regulated category requires admin moderation!
    city: "Whitefield, Bengaluru",
    isHazardous: true,
    hazardDisclosed: true,
    images: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80",
    ],
    scanResult: {
      id: "scn_crt_03",
      listingId: "lst_crt_sony_03",
      detectedBrand: "Sony",
      detectedModel: "Trinitron CPD-E200 Flat Display",
      detectedCondition: "for_parts",
      confidenceScore: 0.96,
      suggestedPriceMin: 450,
      suggestedPriceMax: 750,
      scrapValueEst: 920,
      materialsBreakdown: [
        { name: "Copper deflection yoke wire", weightKg: 1.15, ratePerKg: 645, estimatedValue: 741.75 },
        { name: "Steel shielding chassis", weightKg: 3.4, ratePerKg: 42, estimatedValue: 142.8 },
      ],
      detectedFlaws: [
        "High voltage flyback transformer inactive",
        "Lead-oxide glass envelope (regulated disposal)",
      ],
      isHazardous: true,
      hazardType: "Leaded Glass & HV Capacitor",
      modelVersion: "vision-e-waste-v1.4",
      createdAt: new Date().toISOString(),
    },
    viewsCount: 89,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "lst_swollen_battery_04",
    sellerId: "usr_buyer_ravi",
    sellerName: "Ravi Kumar",
    sellerTrust: 4.9,
    categoryId: "cat_components_pcbs",
    categoryName: "Components & PCBs",
    title: "Lenovo ThinkPad 68+ 72Wh Battery (Cell Swelling Detected)",
    description: "External 6-cell battery pack for ThinkPad T470/T480. Outer casing bulging slightly. BMS board is functioning with 10.8V rail intact, but pouch cells require certified battery recyclers. Listed for raw cobalt/lithium extraction facility.",
    condition: "for_parts",
    suggestedPrice: 150,
    suggestedPriceMin: 100,
    suggestedPriceMax: 200,
    askingPrice: 150,
    scrapWeightKg: 0.36,
    scrapValueEst: 85,
    status: "flagged", // Flagged for hazardous inspection in admin console
    city: "HSR Layout, Bengaluru",
    isHazardous: true,
    hazardDisclosed: true,
    images: [
      "https://images.unsplash.com/photo-1619725002198-6a689b72f41d?auto=format&fit=crop&w=900&q=80",
    ],
    scanResult: {
      id: "scn_bat_04",
      listingId: "lst_swollen_battery_04",
      detectedBrand: "Lenovo ThinkPad",
      detectedModel: "Battery 68+ (0C52862)",
      detectedCondition: "for_parts",
      confidenceScore: 0.98,
      suggestedPriceMin: 100,
      suggestedPriceMax: 200,
      scrapValueEst: 85,
      materialsBreakdown: [
        { name: "BMS Circuit Board (Gold contacts)", weightKg: 0.04, ratePerKg: 1480, estimatedValue: 59.2 },
        { name: "Nickel & Aluminum cell tabs", weightKg: 0.08, ratePerKg: 320, estimatedValue: 25.6 },
      ],
      detectedFlaws: [
        "Visible pouch expansion / cell swelling",
        "Hazardous chemical alert: Lithium Cobalt Oxide",
      ],
      isHazardous: true,
      hazardType: "Swollen Lithium-Ion Pouch Cells",
      modelVersion: "vision-e-waste-v1.4",
      createdAt: new Date().toISOString(),
    },
    viewsCount: 54,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: "lst_pcb_bundle_05",
    sellerId: "usr_seller_priya",
    sellerName: "Priya Sharma",
    sellerTrust: 4.8,
    categoryId: "cat_components_pcbs",
    categoryName: "Components & PCBs",
    title: "Telecom Grade PCB Scrap Bundle (Gold-Plated Contacts / 2.8 kg)",
    description: "Depopulated server motherboards and telecom rack backplanes. High concentration of gold finger edge connectors and immersion gold test pads. Perfect for certified hydrometallurgical or pyrometallurgical precious metal recovery.",
    condition: "for_parts",
    suggestedPrice: 3800,
    suggestedPriceMin: 3400,
    suggestedPriceMax: 4300,
    askingPrice: 3800,
    scrapWeightKg: 2.8,
    scrapValueEst: 4144,
    status: "active",
    city: "Jayanagar, Bengaluru",
    isHazardous: false,
    hazardDisclosed: false,
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=900&q=80",
    ],
    scanResult: {
      id: "scn_pcb_05",
      listingId: "lst_pcb_bundle_05",
      detectedBrand: "Cisco & Huawei Enterprise",
      detectedModel: "Multi-layer High-Tg FR4 Telecom Boards",
      detectedCondition: "for_parts",
      confidenceScore: 0.95,
      suggestedPriceMin: 3400,
      suggestedPriceMax: 4300,
      scrapValueEst: 4144,
      materialsBreakdown: [
        { name: "Gold-finger edge connectors", weightKg: 2.8, ratePerKg: 1480, estimatedValue: 4144 },
      ],
      detectedFlaws: [
        "De-soldered electrolytic capacitors",
        "Intact gold plating traces on edge pins",
      ],
      isHazardous: false,
      modelVersion: "vision-e-waste-v1.4",
      createdAt: new Date().toISOString(),
    },
    viewsCount: 420,
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
  },
  {
    id: "lst_logitech_mouse_06",
    sellerId: "usr_buyer_ravi",
    sellerName: "Ravi Kumar",
    sellerTrust: 4.9,
    categoryId: "cat_audio_smalltech",
    categoryName: "Audio & Small Tech",
    title: "Logitech MX Master 2S (Smooth Tracking, Scroll Wheel Loose)",
    description: "Ergonomic flagship Bluetooth mouse. Darkfield sensor works on glass, left/right clicks are crisp. The smart-shift ratchet wheel spring has slipped so it is permanently in free-spin mode. Battery holds charge for 3+ weeks.",
    condition: "partial",
    suggestedPrice: 850,
    suggestedPriceMin: 700,
    suggestedPriceMax: 1050,
    askingPrice: 850,
    scrapWeightKg: 0.14,
    scrapValueEst: 45,
    status: "active",
    city: "BTM Layout, Bengaluru",
    isHazardous: false,
    hazardDisclosed: false,
    images: [
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80",
    ],
    scanResult: {
      id: "scn_logi_06",
      listingId: "lst_logitech_mouse_06",
      detectedBrand: "Logitech",
      detectedModel: "MX Master 2S (Graphite)",
      detectedCondition: "partial",
      confidenceScore: 0.91,
      suggestedPriceMin: 700,
      suggestedPriceMax: 1050,
      scrapValueEst: 45,
      materialsBreakdown: [
        { name: "Micro-PCB with Nordic BLE IC", weightKg: 0.03, ratePerKg: 1100, estimatedValue: 33 },
        { name: "Rechargeable Li-Po 500mAh cell", weightKg: 0.02, ratePerKg: 320, estimatedValue: 6.4 },
      ],
      detectedFlaws: [
        "Ratchet clutch spring disengaged on scroll unit",
        "Thumb grip rubber shows light patina",
      ],
      isHazardous: false,
      modelVersion: "vision-e-waste-v1.4",
      createdAt: new Date().toISOString(),
    },
    viewsCount: 205,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const SEED_ADMIN_ACTIONS: AdminAction[] = [
  {
    id: "act_001",
    adminId: "usr_admin_mehra",
    adminName: "Officer Vikram Mehra",
    actionType: "freeze_escrow",
    targetType: "order",
    targetId: "ord_disp_901",
    targetTitle: "Dispute: Dell Motherboard POST Failure",
    reason: "Buyer opened dispute within 72-hour window: Motherboard does not output signal to external display.",
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "act_002",
    adminId: "usr_admin_mehra",
    adminName: "Officer Vikram Mehra",
    actionType: "approve_listing",
    targetType: "listing",
    targetId: "lst_hp_charger_01",
    targetTitle: "HP 65W Smart AC Adapter",
    reason: "Multi-angle photo verified; frayed wiring disclosed accurately to buyers.",
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];
